### ISSUE TITLE
Can not get PCGR due to redirect to http

### ISSUE THREAD

**Issue by Mijago** [madreflection/MadReflection.BungieNetApi#1]
Hello there,

I jsut tried to get some PCGRs, but sadly its not possible as it throws:
`Unhandled exception. Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.` in `GetResourceAsync`

Code:
`var c =  _client.Destiny2.GetPostGameCarnageReport(123456);`

The problem probably occours because we want to get a "https" url, but bungie redirects us to "http":
We want "https://www.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/123456/", Bungie redirects us to "http://stats.bungie.net/Platform/Destiny2/Stats/PostGameCarnageReport/123456/".

**Comment by bennbenson** [comment]
@Mijago Thank you for bringing this to my attention.  I was able to reproduce the error.

I've added logic to follow redirection once as a temporary solution.  For now, it'll have the overhead of making two requests.

I plan to modify the code generator to make an exception to the base URL for that endpoint so it doesn't have to follow the redirection.  Keep an eye out for another update.

**Comment by bennbenson** [comment]
I've published new NuGet packages, version 0.1.4.

**Comment by bennbenson** [comment]
`Destiny2.GetPostGameCarnageReport` now directly requests from http://stats.bungie.net/ so it doesn't have to handle a redirect.

Published Nuget packages version 0.1.5.
